# ✅ 공통 설정 (포트 기본값 및 활성 profile)
server:
  port: 8080

spring:
  profiles:
    active: main

---

# ✅ main profile 설정
spring:
  profiles: main

server:
  port: 8080

---

# ✅ develop profile 설정
spring:
  profiles: develop

server:
  port: 8082

spring:
  application:
    name: talkbbungchi

  datasource:
    url: jdbc:mysql://mysql:3306/talkbbungchi
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: userpw

  data:
    mongodb:
      uri: mongodb://mongo:27017/talkbbungchi

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  autoconfigure:
    exclude: []

logging:
  level:
    com.dreamhire.talkbbungchi: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
