server:
  port: 8080

spring:
  application:
    name: talkbbungchi

  datasource:
    url: jdbc:mysql://mysql:3306/talkbbungchi
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: userpw

  data:
    mongodb:
      uri: mongodb://mongo:27017/talkbbungchi

  jpa:
    hibernate:
      ddl-auto: update  # or create / create-drop (개발용)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  autoconfigure:
    exclude: []  # 제외 항목 없애기

# 로깅 설정 (선택)
logging:
  level:
    com.dreamhire.talkbbungchi: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
