# ✅ 공통 설정
spring:
  profiles:
    active: main  # 기본 profile

server:
  port: 8080  # 기본 포트

---

# ✅ main profile
spring:
  config:
    activate:
      on-profile: main

server:
  port: 8080

---

# ✅ develop profile
spring:
  config:
    activate:
      on-profile: develop

server:
  port: 8082

spring:
  application:
    name: talkbbungchi

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: [REST_API_KEY]
            client-secret: ""
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    url: jdbc:mysql://mysql:3306/talkbbungchi
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: userpw

  data:
    mongodb:
      uri: mongodb://mongo:27017/talkbbungchi

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  jwt:
    secret: Pv3I8QQlrZbF2R+kjHC9CJjl8OmrTSRtpJhvVeskplNS5UIZIOPm5Mj8aaM40d/ajckp+Edv1dWlSR8z/S5T2g==

  autoconfigure:
    exclude: []

logging:
  level:
    com.dreamhire.talkbbungchi: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
